/**
 * SP-DevControl v2.0.0
 * Local governance layer for AI-assisted development
 *
 * Copyright (c) 2026 Pedro Rojas — SolucionesPro (Ecuador)
 * MIT License — see LICENSE file for details
 */

import { describe, expect, it, vi } from 'vitest'
import { buildInjection } from '../src/injector.js'
import type { DevSentinelConfig } from '../src/types.js'

const mockControls = vi.hoisted(() => [
  {
    id: 'sec-secrets',
    name: 'No hardcoded secrets',
    category: 'security',
    description: 'Blocks hardcoded secrets',
    norm: 'OWASP',
    mode: 'block',
    agentInstructions: '## [Security] No Hardcoded Secrets\nNEVER write API keys in code.',
  },
  {
    id: 'arch-solid',
    name: 'SOLID principles',
    category: 'architecture',
    description: 'Injects SOLID principles',
    norm: 'SOLID',
    mode: 'inject',
    agentInstructions: '## [Architecture] SOLID\nSingle Responsibility principle.',
  },
])

vi.mock('../src/catalog/controls.js', () => ({
  getActiveControls: () => mockControls,
}))

function sampleConfig(): DevSentinelConfig {
  return {
    project: 'test-project',
    version: '2.1.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    stack: ['node', 'typescript'],
    agents: { allowed: ['claude', 'cursor'], default: 'claude' },
    scope: { allowed: ['src', 'tests'], protected: ['src/auth', '.env'], watchIgnore: ['node_modules'] },
    rules: {
      blockDeletes: true,
      requireApproval: true,
      autoCommit: false,
      requireMessage: true,
      maxFilesPerChange: 10,
    },
    git: { mainBranch: 'main', rejectedBranchPrefix: 'rejected/', commitPrefix: 'DEV' },
    controls: {
      security: ['sec-secrets'],
      architecture: ['arch-solid'],
      commits: [],
      testing: [],
      documentation: [],
      skills: [],
      memory: [],
      privacy: [],
    },
    skills: {
      allowedTools: ['Read', 'Write', 'Edit', 'Grep', 'Glob', 'Bash'],
      approvalRequired: ['WebSearch', 'WebFetch'],
      blockedTools: ['computer'],
      blockedBashPatterns: ['rm -rf'],
      allowedDomains: ['github.com'],
      allowedMcpServers: ['devcontrol'],
    },
    memory: {
      scanBeforeSession: true,
      redactSecretsInContext: true,
      requireApprovalForMemoryWrites: true,
      retentionDays: 30,
      sessionTokenBudget: 100000,
      tokenAlertThreshold: 80000,
    },
    structure: 'flat',
  }
}

describe('injector', () => {
  it('generates CLAUDE.md with project metadata, governance rules, and agent instructions', () => {
    const result = buildInjection(sampleConfig())
    expect(result.claudeMd).toContain('# test-project')
    expect(result.claudeMd).toContain('SP-DevControl Governance Rules')
    expect(result.claudeMd).toContain('Never delete files')
    expect(result.claudeMd).toContain('Always version changes')
    expect(result.claudeMd).toContain('Await approval')
    expect(result.claudeMd).toContain('claude, cursor')
    expect(result.claudeMd).toContain('AUTHORIZED: src, tests')
    expect(result.claudeMd).toContain('PROTECTED (never modify): src/auth, .env')
    expect(result.claudeMd).toContain('node · typescript')
    expect(result.claudeMd).toContain('[Security] No Hardcoded Secrets')
    expect(result.claudeMd).toContain('[Architecture] SOLID')
    expect(result.claudeMd).toContain('NEVER write API keys in code.')
    expect(result.claudeMd).toContain('Single Responsibility principle.')
    expect(result.claudeMd).toContain('SP-DevControl 2.1.0')
  })

  it('generates .cursorrules with authorized scope and core rules', () => {
    const result = buildInjection(sampleConfig())
    expect(result.cursorrules).toContain('# test-project \u2014 Cursor Rules')
    expect(result.cursorrules).toContain('Never delete files')
    expect(result.cursorrules).toContain('Present a plan before writing code')
    expect(result.cursorrules).toContain('authorized scope: src, tests')
    expect(result.cursorrules).toContain('[Security] No Hardcoded Secrets')
    expect(result.cursorrules).toContain('[Architecture] SOLID')
    expect(result.cursorrules).toContain('Generated by DevSentinel')
  })

  it('generates .windsurfrules identical to .cursorrules content', () => {
    const result = buildInjection(sampleConfig())
    expect(result.windsurfrules).toBe(result.cursorrules)
    expect(result.windsurfrules).toContain('# test-project \u2014 Cursor Rules')
    expect(result.windsurfrules).toContain('Never delete files')
    expect(result.windsurfrules).toContain('authorized scope: src, tests')
  })

  it('generates opencode.json with only MCP config when no inference is configured', () => {
    const result = buildInjection(sampleConfig())
    const parsed = JSON.parse(result.opencodeJson)
    // Without inference config: no hardcoded provider or model — just the MCP integration
    expect(parsed.provider).toBeUndefined()
    expect(parsed.model).toBeUndefined()
    // opencode uses "mcp" (type: "remote", enabled) not "mcpServers"
    expect(parsed.mcp.devcontrol).toEqual({ type: 'remote', url: 'http://localhost:7893/mcp', enabled: true })
  })

  it('generates opencode.json with custom provider when inference is configured', () => {
    const config = sampleConfig()
    config.inference = {
      providerName: 'my-ollama',
      baseURL: 'http://localhost:11434/v1',
      apiKey: 'ollama',
      model: 'my-ollama/qwen2.5-coder:7b',
    }
    const result = buildInjection(config)
    const parsed = JSON.parse(result.opencodeJson)
    expect(parsed.model).toBe('my-ollama/qwen2.5-coder:7b')
    expect(parsed.provider['my-ollama'].options.baseURL).toBe('http://localhost:11434/v1')
    expect(parsed.provider['my-ollama'].options.apiKey).toBe('ollama')
    expect(parsed.mcp.devcontrol).toEqual({ type: 'remote', url: 'http://localhost:7893/mcp', enabled: true })
  })

  it('generates MCP config for Cursor with devcontrol SSE server', () => {
    const result = buildInjection(sampleConfig())
    expect(result.mcpConfig).toEqual({
      mcpServers: {
        devcontrol: {
          type: 'sse',
          url: 'http://localhost:7893/mcp',
        },
      },
    })
  })
})
