/**
 * SP-DevControl v2.0.0
 * Local governance layer for AI-assisted development
 *
 * Copyright (c) 2026 Pedro Rojas — SolucionesPro (Ecuador)
 * MIT License — see LICENSE file for details
 */

import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'fs'
import { join, resolve } from 'path'
import { VERSION } from './version.js'
import type { DevSentinelConfig, InjectionResult } from './types.js'
import { getActiveControls } from './catalog/controls.js'
import { CONTROL_DIR } from './paths.js'
import { type GatesFile, getGateSummaryTable, loadGates } from './gates.js'

const AUTO_GENERATED_MARKER = 'SP-DevControl'

interface WriteResult {
  path: string
  action: 'written' | 'skipped-custom' | 'created'
}

function isAutoGenerated(filePath: string): boolean {
  if (!existsSync(filePath)) return false
  try {
    const content = readFileSync(filePath, 'utf-8')
    return content.includes(AUTO_GENERATED_MARKER)
  } catch {
    return false
  }
}

function safeWriteFile(filePath: string, content: string): WriteResult {
  if (isAutoGenerated(filePath)) {
    writeFileSync(filePath, content, 'utf-8')
    return { path: filePath, action: 'written' }
  }
  if (existsSync(filePath)) {
    return { path: filePath, action: 'skipped-custom' }
  }
  writeFileSync(filePath, content, 'utf-8')
  return { path: filePath, action: 'created' }
}

export function buildInjection(config: DevSentinelConfig, projectRoot?: string): InjectionResult {
  const controls = getActiveControls(config)
  const injectable = controls.filter(c => c.mode === 'inject' || c.mode === 'both' || c.mode === 'block')

  const sections = injectable.map(c => {
    let instructions = c.agentInstructions
    instructions = instructions.replace('{{project_name}}', config.project)
    instructions = instructions.replace('{{scope_allowed}}', config.scope.allowed.join(', '))
    instructions = instructions.replace('{{scope_protected}}', config.scope.protected.join(', '))
    instructions = instructions.replace('{{coverage_threshold}}', String(config.testing?.coverageThreshold ?? 50))
    return instructions
  })

  const agentsList = config.agents.allowed.join(', ')
  const scopeAllowed = config.scope.allowed.join(', ')

  const claudeMd = buildClaudeMd(config, sections, agentsList, scopeAllowed, projectRoot)
  const cursorrules = buildCursorrules(config, sections)
  const copilotInstructions = buildCopilotInstructions(config, sections)
  const agentSettings = buildAgentSettings(config)
  const opencodeJson = buildOpencodeJson(config)
  const mcpConfig = buildMcpConfig()

  return {
    claudeMd,
    cursorrules,
    windsurfrules: cursorrules,
    copilotInstructions,
    agentSettings,
    opencodeJson,
    mcpConfig,
  }
}

function buildGatesSection(projectRoot?: string): string {
  if (projectRoot) {
    const gatesFile = resolve(projectRoot, CONTROL_DIR, 'gates.json')
    if (existsSync(gatesFile)) {
      return ''
    }
  }
  return ''
}

function buildClaudeMd(config: DevSentinelConfig, sections: string[], agents: string, scope: string, projectRoot?: string): string {
  return `# ${config.project} — Agent Instructions (SP-DevControl)

> **Governance ACTIVE** — ${Object.values(config.controls).flat().length} controls enforced · ${config.stack.join(', ')}
> All file changes require human approval. Protected paths are enforced.

${buildGatesSection(projectRoot)}

## RULES
1. Never delete files. Create versions (file.v2.ts)
2. Never touch protected paths: ${config.scope.protected.join(', ')}
3. Stay in scope: ${scope}
4. Await user approval before applying changes
5. Authorized agents: ${agents}

--- 
${sections.join('\n\n')}
--- 
SP-DevControl ${VERSION}`
}

function buildCursorrules(config: DevSentinelConfig, sections: string[]): string {
  return `# ${config.project} — Cursor Rules (SP-DevControl)

> **Governance ACTIVE** — All file changes require human approval.

RULES:
1. Never delete files. Use .v2 suffix
2. Present plan before modifying >3 files
3. Stay in: ${config.scope.allowed.join(', ')}
4. Protected: ${config.scope.protected.join(', ')}
5. Await user approval before applying changes
${sections.map(s => s.split('\n').filter(l => l.startsWith('-')).join('\n')).join('\n')}
`
}

function buildCopilotInstructions(config: DevSentinelConfig, sections: string[]): string {
  return `# ${config.project} — Copilot (SP-DevControl)

> **Governance ACTIVE** — All file changes require human approval.

Project: ${config.project} | ${config.stack.join(', ')}
Governance: SP-DevControl

RULES:
1. Never suggest deleting files
2. Changes need user approval
3. Scope: ${config.scope.allowed.join(', ')}
4. Protected: ${config.scope.protected.join(', ')}
5. Await user approval before applying changes
`
}

function buildAgentSettings(config: DevSentinelConfig): Record<string, unknown> {
  return {
    permissions: {
      allow: config.skills.allowedTools.map(t => `${t}(*)`),
      deny: config.skills.blockedTools.map(t => `${t}(*)`),
    },
    mcpServers: {
      allowed: config.skills.allowedMcpServers,
      devcontrol: {
        type: 'sse',
        url: 'http://localhost:7893/mcp',
      },
    },
    spDevControl: {
      project: config.project,
      version: config.version,
      governanceActive: true,
    },
  }
}

function buildOpencodeJson(config: DevSentinelConfig): string {
  const inf = config.inference
  const mcp = {
    devcontrol: {
      type: 'remote',
      url: 'http://localhost:7893/mcp',
      enabled: true,
    },
  }

  // With user-configured inference endpoint
  if (inf?.baseURL) {
    const providerName = inf.providerName ?? 'local-ai'
    const cfg = {
      $schema: 'https://opencode.ai/config.json',
      model: inf.model ?? `${providerName}/default`,
      provider: {
        [providerName]: {
          npm: inf.npm ?? '@ai-sdk/openai-compatible',
          options: {
            apiKey: inf.apiKey ?? 'local',
            baseURL: inf.baseURL,
          },
        },
      },
      mcp,
    }
    return JSON.stringify(cfg, null, 2)
  }

  // Generic: MCP integration only — user configures their own AI provider
  const cfg = {
    $schema: 'https://opencode.ai/config.json',
    // model: "provider-name/model-id"  — set your preferred model here
    mcp,
  }
  return JSON.stringify(cfg, null, 2)
}

function buildMcpConfig(): Record<string, unknown> {
  return {
    mcpServers: {
      devcontrol: {
        type: 'sse',
        url: 'http://localhost:7893/mcp',
      },
    },
  }
}

export function writeInjectionFiles(result: InjectionResult, projectRoot: string, config: DevSentinelConfig): WriteResult[] {
  const results: WriteResult[] = []

  const injectedDir = join(projectRoot, '.devcontrol', 'injected')
  if (!existsSync(injectedDir)) mkdirSync(injectedDir, { recursive: true })

  const cursorDir = join(projectRoot, '.cursor')
  if (!existsSync(cursorDir)) mkdirSync(cursorDir, { recursive: true })

  const windsurfDir = join(projectRoot, '.windsurf')
  if (!existsSync(windsurfDir)) mkdirSync(windsurfDir, { recursive: true })

  const mcpConfigJson = JSON.stringify(result.mcpConfig, null, 2)

  const files: Array<[string, string]> = [
    [join(projectRoot, 'CLAUDE.md'), result.claudeMd],
    [join(projectRoot, '.cursorrules'), result.cursorrules],
    [join(projectRoot, '.windsurfrules'), result.windsurfrules],
    [join(injectedDir, 'copilot-instructions.md'), result.copilotInstructions],
    [join(injectedDir, 'agent-settings.json'), JSON.stringify(result.agentSettings, null, 2)],
    [join(projectRoot, 'opencode.json'), result.opencodeJson],
    [join(cursorDir, 'mcp.json'), mcpConfigJson],
    [join(windsurfDir, 'mcp.json'), mcpConfigJson],
  ]

  for (const [filePath, content] of files) {
    results.push(safeWriteFile(filePath, content))
  }

  return results
}
