/**
 * SP-DevControl v2.0.0
 * Local governance layer for AI-assisted development
 *
 * Copyright (c) 2026 Pedro Rojas — SolucionesPro (Ecuador)
 * MIT License — see LICENSE file for details
 */

import { writeFileSync, mkdirSync, existsSync } from 'fs'
import { join } from 'path'
import { VERSION } from './version.js'
import type { DevSentinelConfig, InjectionResult } from './types.js'
import { getActiveControls } from './catalog/controls.js'

export function buildInjection(config: DevSentinelConfig): InjectionResult {
  const controls = getActiveControls(config)
  const injectable = controls.filter(c => c.mode === 'inject' || c.mode === 'both' || c.mode === 'block')

  const sections = injectable.map(c => {
    let instructions = c.agentInstructions
    instructions = instructions.replace('{{project_name}}', config.project)
    instructions = instructions.replace('{{scope_allowed}}', config.scope.allowed.join(', '))
    instructions = instructions.replace('{{scope_protected}}', config.scope.protected.join(', '))
    return instructions
  })

  const agentsList = config.agents.allowed.join(', ')
  const scopeAllowed = config.scope.allowed.join(', ')

  const claudeMd = buildClaudeMd(config, sections, agentsList, scopeAllowed)
  const cursorrules = buildCursorrules(config, sections)
  const copilotInstructions = buildCopilotInstructions(config, sections)
  const agentSettings = buildAgentSettings(config)
  const opencodeJson = buildOpencodeJson(config)
  const mcpConfig = buildMcpConfig()

  return {
    claudeMd,
    cursorrules,
    windsurfrules: cursorrules,
    copilotInstructions,
    agentSettings,
    opencodeJson,
    mcpConfig,
  }
}

function buildClaudeMd(config: DevSentinelConfig, sections: string[], agents: string, scope: string): string {
  return `# ${config.project} — Agent Instructions (generated by SP-DevControl)
> Auto-generated — do not edit manually. Run \`sp-devcontrol inject\` to regenerate.
> Active controls: ${Object.values(config.controls).flat().length} | Stack: ${config.stack.join(', ')}

## SP-DevControl Governance Rules
This project is governed by SP-DevControl. You MUST follow these rules without exception:

1. **Never delete files** — create new versions instead (file.v2.ts, file.backup.ts)
2. **Always version changes** — describe what changed and why before each modification
3. **Await approval** — present changes and wait for explicit user approval before applying

## Authorized agents
${agents}

## File scope
AUTHORIZED: ${scope}
PROTECTED (never modify): ${config.scope.protected.join(', ')}

## Stack
${config.stack.join(' · ')}

---

${sections.join('\n\n---\n\n')}

---
*SP-DevControl ${VERSION} — Generated ${new Date().toISOString()}*
`
}

function buildCursorrules(config: DevSentinelConfig, sections: string[]): string {
  return `# ${config.project} — Cursor Rules (SP-DevControl)
# Auto-generated — do not edit manually

## Core rules
- Never delete files. Create new versions with suffixes (.v2, .backup, .old)
- Present a plan before writing code — describe what you'll change and why
- Stay within authorized scope: ${config.scope.allowed.join(', ')}

${sections.join('\n\n')}

# Generated by DevSentinel ${new Date().toISOString()}
`
}

function buildCopilotInstructions(config: DevSentinelConfig, sections: string[]): string {
  return `# ${config.project} — GitHub Copilot Instructions (SP-DevControl)
# Auto-generated — do not edit manually

You are assisting with ${config.project} (${config.stack.join(', ')}).
Project is governed by SP-DevControl. Key constraints:
- Never suggest deleting files — propose versioned alternatives
- All changes need user review before applying
- Authorized scope: ${config.scope.allowed.join(', ')}

${sections.join('\n\n')}
`
}

function buildAgentSettings(config: DevSentinelConfig): Record<string, unknown> {
  return {
    permissions: {
      allow: config.skills.allowedTools.map(t => `${t}(*)`),
      deny: config.skills.blockedTools.map(t => `${t}(*)`),
    },
    mcpServers: {
      allowed: config.skills.allowedMcpServers,
      devcontrol: {
        type: 'sse',
        url: 'http://localhost:7893/mcp',
      },
    },
    spDevControl: {
      project: config.project,
      version: config.version,
      governanceActive: true,
    },
  }
}

function buildOpencodeJson(config: DevSentinelConfig): string {
  const inf = config.inference
  const mcp = {
    devcontrol: {
      type: 'remote',
      url: 'http://localhost:7893/mcp',
      enabled: true,
    },
  }

  // With user-configured inference endpoint
  if (inf?.baseURL) {
    const providerName = inf.providerName ?? 'local-ai'
    const cfg = {
      $schema: 'https://opencode.ai/config.json',
      model: inf.model ?? `${providerName}/default`,
      provider: {
        [providerName]: {
          npm: inf.npm ?? '@ai-sdk/openai-compatible',
          options: {
            apiKey: inf.apiKey ?? 'local',
            baseURL: inf.baseURL,
          },
        },
      },
      mcp,
    }
    return JSON.stringify(cfg, null, 2)
  }

  // Generic: MCP integration only — user configures their own AI provider
  const cfg = {
    $schema: 'https://opencode.ai/config.json',
    // model: "provider-name/model-id"  — set your preferred model here
    mcp,
  }
  return JSON.stringify(cfg, null, 2)
}

function buildMcpConfig(): Record<string, unknown> {
  return {
    mcpServers: {
      devcontrol: {
        type: 'sse',
        url: 'http://localhost:7893/mcp',
      },
    },
  }
}

export function writeInjectionFiles(result: InjectionResult, projectRoot: string, config: DevSentinelConfig): string[] {
  const written: string[] = []

  const injectedDir = join(projectRoot, '.devcontrol', 'injected')
  if (!existsSync(injectedDir)) mkdirSync(injectedDir, { recursive: true })

  const cursorDir = join(projectRoot, '.cursor')
  if (!existsSync(cursorDir)) mkdirSync(cursorDir, { recursive: true })

  const windsurfDir = join(projectRoot, '.windsurf')
  if (!existsSync(windsurfDir)) mkdirSync(windsurfDir, { recursive: true })

  const mcpConfigJson = JSON.stringify(result.mcpConfig, null, 2)

  const files: Array<[string, string]> = [
    [join(projectRoot, 'CLAUDE.md'), result.claudeMd],
    [join(projectRoot, '.cursorrules'), result.cursorrules],
    [join(projectRoot, '.windsurfrules'), result.windsurfrules],
    [join(injectedDir, 'copilot-instructions.md'), result.copilotInstructions],
    [join(injectedDir, 'agent-settings.json'), JSON.stringify(result.agentSettings, null, 2)],
    [join(projectRoot, 'opencode.json'), result.opencodeJson],
    [join(cursorDir, 'mcp.json'), mcpConfigJson],
    [join(windsurfDir, 'mcp.json'), mcpConfigJson],
  ]

  for (const [filePath, content] of files) {
    writeFileSync(filePath, content, 'utf-8')
    written.push(filePath)
  }

  return written
}
