import { writeFileSync, mkdirSync, existsSync } from 'fs'
import { join } from 'path'
import type { DevSentinelConfig, InjectionResult } from './types.js'
import { getActiveControls } from './catalog/controls.js'

export function buildInjection(config: DevSentinelConfig): InjectionResult {
  const controls = getActiveControls(config)
  const injectable = controls.filter(c => c.mode === 'inject' || c.mode === 'both' || c.mode === 'block')

  const sections = injectable.map(c => {
    let instructions = c.agentInstructions
    instructions = instructions.replace('{{project_name}}', config.project)
    instructions = instructions.replace('{{scope_allowed}}', config.scope.allowed.join(', '))
    instructions = instructions.replace('{{scope_protected}}', config.scope.protected.join(', '))
    return instructions
  })

  const agentsList = config.agents.allowed.join(', ')
  const scopeAllowed = config.scope.allowed.join(', ')

  const claudeMd = buildClaudeMd(config, sections, agentsList, scopeAllowed)
  const cursorrules = buildCursorrules(config, sections)
  const copilotInstructions = buildCopilotInstructions(config, sections)
  const agentSettings = buildAgentSettings(config)

  return {
    claudeMd,
    cursorrules,
    windsurfrules: cursorrules,
    copilotInstructions,
    agentSettings,
  }
}

function buildClaudeMd(config: DevSentinelConfig, sections: string[], agents: string, scope: string): string {
  return `# ${config.project} — Agent Instructions (generated by SP-DevControl)
> Auto-generated — do not edit manually. Run \`sp-devcontrol inject\` to regenerate.
> Active controls: ${Object.values(config.controls).flat().length} | Stack: ${config.stack.join(', ')}

## SP-DevControl Governance Rules
This project is governed by SP-DevControl. You MUST follow these rules without exception:

1. **Never delete files** — create new versions instead (file.v2.ts, file.backup.ts)
2. **Always version changes** — describe what changed and why before each modification
3. **Await approval** — present changes and wait for explicit user approval before applying

## Authorized agents
${agents}

## File scope
AUTHORIZED: ${scope}
PROTECTED (never modify): ${config.scope.protected.join(', ')}

## Stack
${config.stack.join(' · ')}

---

${sections.join('\n\n---\n\n')}

---
*SP-DevControl v1.0.0 — Generated ${new Date().toISOString()}*
`
}

function buildCursorrules(config: DevSentinelConfig, sections: string[]): string {
  return `# ${config.project} — Cursor Rules (SP-DevControl)
# Auto-generated — do not edit manually

## Core rules
- Never delete files. Create new versions with suffixes (.v2, .backup, .old)
- Present a plan before writing code — describe what you'll change and why
- Stay within authorized scope: ${config.scope.allowed.join(', ')}

${sections.join('\n\n')}

# Generated by DevSentinel ${new Date().toISOString()}
`
}

function buildCopilotInstructions(config: DevSentinelConfig, sections: string[]): string {
  return `# ${config.project} — GitHub Copilot Instructions (SP-DevControl)
# Auto-generated — do not edit manually

You are assisting with ${config.project} (${config.stack.join(', ')}).
Project is governed by SP-DevControl. Key constraints:
- Never suggest deleting files — propose versioned alternatives
- All changes need user review before applying
- Authorized scope: ${config.scope.allowed.join(', ')}

${sections.join('\n\n')}
`
}

function buildAgentSettings(config: DevSentinelConfig): Record<string, unknown> {
  return {
    permissions: {
      allow: config.skills.allowedTools.map(t => `${t}(*)`),
      deny: config.skills.blockedTools.map(t => `${t}(*)`),
    },
    mcpServers: {
      allowed: config.skills.allowedMcpServers,
    },
    spDevControl: {
      project: config.project,
      version: config.version,
      governanceActive: true,
    },
  }
}

export function writeInjectionFiles(result: InjectionResult, projectRoot: string, config: DevSentinelConfig): string[] {
  const written: string[] = []

  const injectedDir = join(projectRoot, '.devcontrol', 'injected')
  if (!existsSync(injectedDir)) mkdirSync(injectedDir, { recursive: true })

  const files: Array<[string, string]> = [
    [join(projectRoot, 'CLAUDE.md'), result.claudeMd],
    [join(projectRoot, '.cursorrules'), result.cursorrules],
    [join(projectRoot, '.windsurfrules'), result.windsurfrules],
    [join(injectedDir, 'copilot-instructions.md'), result.copilotInstructions],
    [join(injectedDir, 'agent-settings.json'), JSON.stringify(result.agentSettings, null, 2)],
  ]

  for (const [filePath, content] of files) {
    writeFileSync(filePath, content, 'utf-8')
    written.push(filePath)
  }

  return written
}
