/**
 * SP-DevControl v2.0.0
 * Local governance layer for AI-assisted development
 *
 * Copyright (c) 2026 Pedro Rojas — SolucionesPro (Ecuador)
 * MIT License — see LICENSE file for details
 */

import { writeFileSync, mkdirSync, existsSync } from 'fs'
import { join } from 'path'
import type { SessionReport, Session, ChangeSet } from './types.js'
import { VERSION } from './version.js'

export function buildSessionReport(session: Session, changes: ChangeSet[]): SessionReport {
  const approved = changes.filter(c => c.status === 'approved' || c.status === 'partial')
  const rejected = changes.filter(c => c.status === 'rejected')
  const partial = changes.filter(c => c.status === 'partial')

  const allApprovedFiles = approved.flatMap(c => c.files.filter(f => f.eventType !== 'deleted_attempt'))
  const deleteAttempts = changes.flatMap(c => c.files.filter(f => f.eventType === 'deleted_attempt').map(f => f.filepath))
  const depsAdded = [...new Set(approved.flatMap(c => c.depsAdded))]
  const controlViolations = changes.reduce((sum, c) => sum + c.controlViolations.length, 0)

  return {
    session,
    changes,
    summary: {
      proposed: changes.length,
      approved: approved.length,
      rejected: rejected.length,
      partial: partial.length,
      filesModified: allApprovedFiles.length,
      deleteAttempts: deleteAttempts.length,
      depsAdded,
      controlViolations,
    },
  }
}

export function renderMarkdownReport(report: SessionReport): string {
  const { session, changes, summary } = report
  const startDate = new Date(session.startedAt).toLocaleString()
  const endDate = session.endedAt ? new Date(session.endedAt).toLocaleString() : 'In progress'

  const approvedChanges = changes.filter(c => c.status === 'approved' || c.status === 'partial')
  const rejectedChanges = changes.filter(c => c.status === 'rejected')

  const approvedTable = approvedChanges.length > 0
    ? [
        '| ID | Files | Lines | Risk | Commit |',
        '|---|---|---|---|---|',
        ...approvedChanges.map(c => {
          const files = c.files.filter(f => f.eventType !== 'deleted_attempt').map(f => f.filepath).join(', ')
          const lines = `+${c.files.reduce((s, f) => s + f.linesAdded, 0)}/-${c.files.reduce((s, f) => s + f.linesRemoved, 0)}`
          const commit = c.commitHash ? c.commitHash.slice(0, 8) : '—'
          return `| ${c.id} | ${files || '—'} | ${lines} | ${c.riskLevel} | \`${commit}\` |`
        }),
      ].join('\n')
    : '_None_'

  const rejectedTable = rejectedChanges.length > 0
    ? [
        '| ID | Files | Reason |',
        '|---|---|---|',
        ...rejectedChanges.map(c => {
          const files = c.files.map(f => f.filepath).join(', ')
          const reason = c.rejectedBranch ? `Branch: \`${c.rejectedBranch}\`` : 'Rejected by user'
          return `| ${c.id} | ${files || '—'} | ${reason} |`
        }),
      ].join('\n')
    : '_None_'

  const deleteSection = changes.flatMap(c => c.files.filter(f => f.eventType === 'deleted_attempt'))
  const deleteLines = deleteSection.length > 0
    ? deleteSection.map(f => `- \`${f.filepath}\``).join('\n')
    : '_None_'

  const violationsSection = changes.flatMap(c => c.controlViolations)
  const violationsLines = violationsSection.length > 0
    ? violationsSection.map(v => `- **[${v.controlId}]** ${v.message}${v.filepath ? ` (\`${v.filepath}\`)` : ''}`).join('\n')
    : '_No violations_'

  return `# Session ${session.id} — Report

**Project:** ${session.project}
**Agent:** ${session.agent}
**Mode:** ${session.mode}
**Start:** ${startDate}
**End:** ${endDate}

---

## Summary

| Metric | Value |
|---|---|
| Changes proposed | ${summary.proposed} |
| Approved | ${summary.approved} |
| Rejected | ${summary.rejected} |
| Partial | ${summary.partial} |
| Files modified | ${summary.filesModified} |
| Delete attempts blocked | ${summary.deleteAttempts} |
| New dependencies | ${summary.depsAdded.length > 0 ? summary.depsAdded.join(', ') : '—'} |
| Control violations | ${summary.controlViolations} |

---

## Approved changes

${approvedTable}

---

## Rejected changes

${rejectedTable}

---

## Delete attempts blocked

${deleteLines}

---

## Control violations detected

${violationsLines}

---

_Generated by SP-DevControl ${VERSION} · ${new Date().toISOString()}_
`
}

export function saveReport(report: SessionReport, projectRoot: string): string {
  const reportsDir = join(projectRoot, '.devcontrol', 'reports')
  if (!existsSync(reportsDir)) mkdirSync(reportsDir, { recursive: true })

  const filename = `${report.session.id}-report.md`
  const filepath = join(reportsDir, filename)
  const content = renderMarkdownReport(report)
  writeFileSync(filepath, content, 'utf-8')
  return filepath
}
