import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import type { DevSentinelConfig } from './types.js'

export type EditorTarget = 'claude' | 'opencode' | 'cursor' | 'windsurf' | 'copilot' | 'all'

export interface SkillResult {
  editor: string
  files: Array<{ path: string; content: string; description: string }>
}

function mcpServerBlock(port: number): Record<string, unknown> {
  return {
    devcontrol: {
      type: 'sse',
      url: `http://localhost:${port}/mcp`,
    },
  }
}

function buildClaudeSkills(projectRoot: string, config: DevSentinelConfig, mcpPort?: number): SkillResult {
  const files: SkillResult['files'] = []

  const commandContent = `---
description: SP-DevControl — governance, sessions, change control, compliance
allowed-tools: Bash
---
Run: devcontrol $ARGUMENTS
Use this to: start/close sessions, approve/reject changes, check policy, generate compliance reports.
Examples: /devcontrol session:start --objective "feat X" | /devcontrol project:check | /devcontrol report:compliance
`

  files.push({
    path: join(projectRoot, '.claude', 'commands', 'devcontrol.md'),
    content: commandContent,
    description: 'Claude Code slash command /devcontrol',
  })

  const settingsHook = {
    hooks: {
      PreToolUse: [
        {
          matcher: 'Bash',
          hooks: [
            {
              type: 'command',
              command: 'devcontrol policy:command',
            },
          ],
        },
      ],
    },
  }

  files.push({
    path: join(projectRoot, '.claude', 'settings.json'),
    content: JSON.stringify(settingsHook, null, 2),
    description: 'Claude Code settings with PreToolUse hook for policy enforcement',
  })

  if (mcpPort !== undefined) {
    const mcpConfig = {
      mcpServers: mcpServerBlock(mcpPort),
    }

    files.push({
      path: join(projectRoot, '.claude', 'mcp.json'),
      content: JSON.stringify(mcpConfig, null, 2),
      description: 'Claude Code MCP server configuration',
    })
  }

  return { editor: 'claude', files }
}

function buildOpencodeSkills(projectRoot: string, config: DevSentinelConfig, mcpPort?: number): SkillResult {
  const toolConfig: Record<string, unknown> = {
    tools: {
      devcontrol: {
        type: 'local',
        command: 'devcontrol',
        description: `SP-DevControl governance for ${config.project} — sessions, change control, compliance`,
      },
    },
  }

  if (mcpPort !== undefined) {
    toolConfig.mcpServers = mcpServerBlock(mcpPort)
  }

  return {
    editor: 'opencode',
    files: [
      {
        path: join(projectRoot, 'opencode.json'),
        content: JSON.stringify(toolConfig, null, 2),
        description: 'opencode tool integration for devcontrol CLI',
      },
    ],
  }
}

function buildCursorSkills(projectRoot: string, _config: DevSentinelConfig, mcpPort?: number): SkillResult {
  const files: SkillResult['files'] = []

  if (mcpPort !== undefined) {
    const mcpConfig = {
      mcpServers: mcpServerBlock(mcpPort),
    }

    files.push({
      path: join(projectRoot, '.cursor', 'mcp.json'),
      content: JSON.stringify(mcpConfig, null, 2),
      description: 'Cursor MCP server configuration (0.43+)',
    })
  }

  return { editor: 'cursor', files }
}

function buildWindsurfSkills(projectRoot: string, _config: DevSentinelConfig, mcpPort?: number): SkillResult {
  const files: SkillResult['files'] = []

  if (mcpPort !== undefined) {
    const mcpConfig = {
      mcpServers: mcpServerBlock(mcpPort),
    }

    files.push({
      path: join(projectRoot, '.windsurf', 'mcp.json'),
      content: JSON.stringify(mcpConfig, null, 2),
      description: 'Windsurf MCP server configuration (1.8+)',
    })
  }

  return { editor: 'windsurf', files }
}

function buildCopilotSkills(projectRoot: string, config: DevSentinelConfig, _mcpPort?: number): SkillResult {
  const scopeAllowed = config.scope.allowed.join(', ') || 'src/**'
  const scopeProtected = config.scope.protected.join(', ') || '.env, package.json'
  const stack = config.stack.join(', ') || 'unspecified'
  const blocked = config.skills.blockedBashPatterns.length > 0
    ? config.skills.blockedBashPatterns.join(', ')
    : 'rm -rf, git reset --hard, git push --force'

  const content = `# ${config.project} — GitHub Copilot Instructions (SP-DevControl)
<!-- Auto-generated by SP-DevControl. Run \`devcontrol inject\` to regenerate. -->

## Project
- **Name:** ${config.project}
- **Stack:** ${stack}
- **Governance:** SP-DevControl v${config.version}

## Authorized agents
${config.agents.allowed.join(', ')}

## File scope
- **Authorized:** ${scopeAllowed}
- **Protected (never modify):** ${scopeProtected}

## Core rules
1. Never delete files — create versioned alternatives (.v2, .bak) instead.
2. Present a plan before touching more than 3 files.
3. Do not suggest or run: ${blocked}
4. All changes require explicit user approval before being applied.
5. Stay within authorized file scope at all times.

## SP-DevControl commands
- \`devcontrol session:start --objective "<goal>"\` — open a governed session
- \`devcontrol project:check\` — validate current state against policy
- \`devcontrol report:compliance\` — generate compliance report
- \`devcontrol session:close\` — close session and persist audit trail
`

  return {
    editor: 'copilot',
    files: [
      {
        path: join(projectRoot, '.github', 'copilot-instructions.md'),
        content,
        description: 'GitHub Copilot Chat instructions for SP-DevControl governance',
      },
    ],
  }
}

export function generateSkills(
  projectRoot: string,
  config: DevSentinelConfig,
  mcpPort?: number,
): SkillResult[] {
  return [
    buildClaudeSkills(projectRoot, config, mcpPort),
    buildOpencodeSkills(projectRoot, config, mcpPort),
    buildCursorSkills(projectRoot, config, mcpPort),
    buildWindsurfSkills(projectRoot, config, mcpPort),
    buildCopilotSkills(projectRoot, config, mcpPort),
  ]
}

type JsonObject = Record<string, unknown>

function isJsonObject(v: unknown): v is JsonObject {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

function deepMerge(base: JsonObject, incoming: JsonObject): JsonObject {
  const result: JsonObject = { ...base }

  for (const key of Object.keys(incoming)) {
    const inVal = incoming[key]
    const baseVal = base[key]

    if (isJsonObject(inVal) && isJsonObject(baseVal)) {
      result[key] = deepMerge(baseVal, inVal)
    } else if (Array.isArray(inVal) && Array.isArray(baseVal)) {
      const seen = new Set(baseVal.map(item => JSON.stringify(item)))
      const merged = [...baseVal]
      for (const item of inVal) {
        if (!seen.has(JSON.stringify(item))) {
          merged.push(item)
          seen.add(JSON.stringify(item))
        }
      }
      result[key] = merged
    } else if (!(key in base)) {
      result[key] = inVal
    }
  }

  return result
}

function resolveContent(filePath: string, generated: string): string {
  if (!filePath.endsWith('.json') || !existsSync(filePath)) {
    return generated
  }

  try {
    const existing = JSON.parse(readFileSync(filePath, 'utf-8')) as unknown
    const incoming = JSON.parse(generated) as unknown

    if (isJsonObject(existing) && isJsonObject(incoming)) {
      return JSON.stringify(deepMerge(existing, incoming), null, 2)
    }
  } catch {
    // corrupt or non-object JSON — overwrite
  }

  return generated
}

export function writeSkills(
  projectRoot: string,
  config: DevSentinelConfig,
  target: EditorTarget = 'all',
  mcpPort?: number,
): string[] {
  const allResults = generateSkills(projectRoot, config, mcpPort)

  const results = target === 'all'
    ? allResults
    : allResults.filter(r => r.editor === target)

  const written: string[] = []

  for (const result of results) {
    for (const file of result.files) {
      const dir = dirname(file.path)
      if (!existsSync(dir)) {
        mkdirSync(dir, { recursive: true })
      }

      const content = resolveContent(file.path, file.content)
      writeFileSync(file.path, content, 'utf-8')
      written.push(file.path)
    }
  }

  return written
}
